<a href="https://colab.research.google.com/github/mahekgheewala/Cross_validation/blob/main/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

Importing the Models

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
heart_data = pd.read_csv('/content/heart (1).csv')

In [4]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
heart_data.shape

(303, 14)

In [6]:
# checking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
# Checking the distribution of target variable
heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

1 -----> Defective heart

0 -----> Not Defective heart

In [9]:
# Splitting thr feature and target
X = heart_data.drop(columns='target', axis = 1)
Y = heart_data['target']

In [10]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [11]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


#Train Test Split

Use of Stratify: If Y has:

80% class 0

20% class 1

Then with stratify=Y, both X_train and X_test will also have:

80% class 0

20% class 1


It makes sure that training and testing data get same ratio of both labels

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify = Y, random_state=3)

In [13]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)


Comparing Performance of the Models:(based on train test split)

In [18]:
# List of models:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [19]:
def compare_models():
  for model in models:
    # training the model
    model.fit(X_train, Y_train)
    # evaluating the model
    test_data_prediction = model.predict(X_test)

    accuracy = accuracy_score(Y_test, test_data_prediction)
    print(model, accuracy)

In [20]:
compare_models()

LogisticRegression(max_iter=1000) 0.7868852459016393
SVC(kernel='linear') 0.7704918032786885
KNeighborsClassifier() 0.6557377049180327
RandomForestClassifier() 0.7868852459016393


#Cross Validation

like cross_val_score we also have library named k_fold:

 Difference: in cross: it does all the evaluation itself whereas in k_fold we have to write some code in order to find the accuracy.

Cross Validation

In [21]:
cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000), X, Y, cv=5)

In [22]:
print(cv_score_lr)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]


In [23]:
mean_accuracy1 = sum(cv_score_lr)/len(cv_score_lr)
mean_accuracy1 = mean_accuracy1 * 100
mean_accuracy1 = round(mean_accuracy1,2)
print(mean_accuracy1)

82.83


In [24]:
cv_score_svc = cross_val_score(SVC(kernel='linear'),X, Y, cv=5)
print(cv_score_svc)
mean_accuracy2 = sum(cv_score_svc)/len(cv_score_svc)
mean_accuracy2 = mean_accuracy2 * 100
mean_accuracy2 = round(mean_accuracy2,2)
print(mean_accuracy2)

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83


Instead of doing it seperately, we would create a function that would do it all together

In [25]:
# List of models:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [28]:
def compare_models_cross_validation():
  for model in models:
    cv_score = cross_val_score(model, X,Y,cv=5)
    print(cv_score)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy * 100
    mean_accuracy = round(mean_accuracy, 2)
    print(mean_accuracy, model)

In [29]:
compare_models_cross_validation()

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
82.83 LogisticRegression(max_iter=1000)
[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83 SVC(kernel='linear')
[0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
64.39 KNeighborsClassifier()
[0.80327869 0.8852459  0.78688525 0.81666667 0.78333333]
81.51 RandomForestClassifier()
